In [45]:
import torch
import numpy as np
from time import perf_counter

# Exercise 1

In [13]:
a = torch.full((6,6), 1)
a[1,:] = 2
a[:,1] = 2
a[3:5, 3:5] = 3
a

tensor([[1., 2., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1.],
        [1., 2., 1., 3., 3., 1.],
        [1., 2., 1., 3., 3., 1.],
        [1., 2., 1., 1., 1., 1.]])

In [16]:
a_inv_row = a[:, ::-1]

ValueError: negative step not yet supported

In [11]:
b = torch.empty(13,13)
b[0:6, 0:6] = a
b[7:, 0:6] = 

In [12]:
b

tensor([[ 1.0000e+00,  2.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  7.2016e+22,  4.7428e+30,  0.0000e+00,  0.0000e+00,
          6.6982e-43,  3.1529e-43,  0.0000e+00],
        [ 2.0000e+00,  2.0000e+00,  2.0000e+00,  2.0000e+00,  2.0000e+00,
          2.0000e+00,  0.0000e+00,  1.6149e-07,  1.3567e-19,  2.6700e-06,
          1.3028e-11,  8.2913e-33,  1.3563e-19],
        [ 1.0000e+00,  2.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  2.3878e-06,  1.3028e-11,  1.4588e-19,  4.1531e-05,
          5.4666e+22,  2.5182e-12,  4.1638e-11],
        [ 1.0000e+00,  2.0000e+00,  1.0000e+00,  3.0000e+00,  3.0000e+00,
          1.0000e+00,  1.3563e-19,  1.3563e-19,  4.1411e-11,  2.6077e-09,
          1.0371e-08,  2.3301e-09,  2.7447e-06],
        [ 1.0000e+00,  2.0000e+00,  1.0000e+00,  3.0000e+00,  3.0000e+00,
          1.0000e+00,  9.1672e-33,  1.7325e-01,  1.1258e+24,  1.7136e-10,
          9.1575e-33,  7.1555e+22,  1.0937e-02],
        [ 1.000

# Exercise 2

In [25]:
gauss = torch.empty(20,20).normal_(2, 1)
diag = torch.diag(torch.FloatTensor(range(20)))
d = torch.inverse(gauss) @ diag @ gauss
torch.eig(d)

torch.return_types.eig(
eigenvalues=tensor([[6.0797e-05, 0.0000e+00],
        [9.9999e-01, 0.0000e+00],
        [2.0001e+00, 0.0000e+00],
        [1.9000e+01, 0.0000e+00],
        [3.0000e+00, 0.0000e+00],
        [1.8000e+01, 0.0000e+00],
        [4.0000e+00, 0.0000e+00],
        [1.7000e+01, 0.0000e+00],
        [5.0000e+00, 0.0000e+00],
        [6.0001e+00, 0.0000e+00],
        [7.0000e+00, 0.0000e+00],
        [1.6000e+01, 0.0000e+00],
        [8.0000e+00, 0.0000e+00],
        [9.0001e+00, 0.0000e+00],
        [1.5000e+01, 0.0000e+00],
        [9.9999e+00, 0.0000e+00],
        [1.4000e+01, 0.0000e+00],
        [1.1000e+01, 0.0000e+00],
        [1.2000e+01, 0.0000e+00],
        [1.3000e+01, 0.0000e+00]]),
eigenvectors=tensor([]))

# Exercise 3

In [30]:
g_1 = torch.empty(5000,5000).normal_(2,1)
g_2 = torch.empty(5000,5000).normal_(2,1)
t1 = perf_counter()
g_1 @ g_2
t2 = perf_counter()
print(t2 - t1)

2.8436619279996194


In [32]:
5000**3 / (t2 - t1)

43957405333.31666

# Exercise 4

In [34]:
a.size()[0]

6

In [38]:
def mul_row(t):
    for r in range(t.size()[0]):
        t[r,:] = t[r,:] * (2**r)
    return t

In [39]:
mul_row(a)

tensor([[ 1.,  2.,  1.,  1.,  1.,  1.],
        [ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 4.,  8.,  4.,  4.,  4.,  4.],
        [ 8., 16.,  8., 24., 24.,  8.],
        [16., 32., 16., 48., 48., 16.],
        [32., 64., 32., 32., 32., 32.]])

In [47]:
def mul_row_fast(t):
    nb_rows = t.size()[0]
    exponents = np.arange(nb_rows)
    twos = np.array([2]*nb_rows)
    powers_of_two = torch.from_numpy(twos ** exponents).float()
    powers_of_two = powers_of_two.view(nb_rows, 1)
    print(powers_of_two)
    return t * powers_of_two

In [48]:
test = torch.full((5,5), 1)
mul_row_fast(test)

tensor([[ 1.],
        [ 2.],
        [ 4.],
        [ 8.],
        [16.]])


tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 8.,  8.,  8.,  8.,  8.],
        [16., 16., 16., 16., 16.]])

In [49]:
t3 = perf_counter()
mul_row(g_1)
t4 = perf_counter()
print(t4 - t3)

RuntimeError: Overflow when unpacking long